In [1]:
import json

# Read json file
file = './ggl-data-original.json'
data = json.load(open(file))

In [3]:
data[0]

{'r': 0, 'x': [-1.0, 1.0], 'w': [1.0, 1.0], 'd': [[-0.5, 0.5], [-0.5, 0.5]]}

In [4]:
from jax import Array, jit, grad

import jax.lax
import jax.numpy as jnp
import scipy.special as sps

In [11]:
r = 0
c = sps.legendre(r + 1).c
xs = jnp.real(jnp.roots(jnp.polyder(c)))
xs

Array([], dtype=float32)

In [9]:
jnp.poly(jnp.array([-1, 1]))

Array([ 1.,  0., -1.], dtype=float32)

In [12]:
jnp.roots(jnp.polymul(jnp.array([1, 0, -1]), jnp.polyder(c)))

Array([-1.+0.j,  1.+0.j], dtype=complex64)

In [13]:
def xs(r: int) -> Array:
   c = sps.legendre(r + 1).c
   return jnp.roots(jnp.polymul(jnp.array([1, 0, -1]), jnp.polyder(c)))

In [21]:
jnp.array(data[3]['x']) - jnp.real(xs(3))

Array([ 3.5762787e-07, -5.9604645e-08, -9.9999988e-01, -1.1920929e-07,
        1.0000000e+00], dtype=float32)

In [24]:
data[3]['x']

[-1.0, -0.6546536707079772, 0.0, 0.6546536707079772, 1.0]

In [30]:
jnp.array(data[3]['x']) - jnp.sort(jnp.real(xs(3)))

Array([ 3.5762787e-07, -5.9604645e-08,  0.0000000e+00, -1.1920929e-07,
        1.1920929e-07], dtype=float32)