In [1]:
from jax import Array, jit, grad

import jax.lax
import jax.numpy as jnp
import scipy.special as sps

In [2]:
from ggl import ggl

In [3]:
ggl(1)

(Array([-1.,  0.,  1.], dtype=float64),
 Array([0.33333333, 1.33333333, 0.33333333], dtype=float64),
 Array([[-1.5,  2. , -0.5],
        [-0.5,  0. ,  0.5],
        [ 0.5, -2. ,  1.5]], dtype=float64))

In [13]:
from functools import partial


@partial(jit, static_argnums=(0,))
def discretise(
        f,
        xs,
        ws,
):
    return jnp.sum(jax.vmap(f)(xs) * ws, axis=0)

In [23]:
l = lambda x: x ** 2
discretise(lambda x: x ** 2, jnp.array([1, 2, 3]), jnp.array([1, 1, 1]))

Array(14, dtype=int64)

In [31]:
discretise(l, jnp.array([1, 2, 3]), jnp.array([1, 1, 1]))

Array(14, dtype=int64)

In [33]:
xs, ws, dij = ggl(3)

In [39]:
discretise(l, xs * 3, ws)

Array(6., dtype=float64)